// data123 {
//    status: 200,
//    statusText: 'OK',
//    headers: AxiosHeaders {
//      'x-powered-by': 'Express',
//      'access-control-allow-origin': 'http://localhost:3000',
//      vary: 'Origin',
//      'access-control-allow-credentials': 'true',
//      'content-type': 'application/json; charset=utf-8',
//      'content-length': '74',
//      etag: 'W/"4a-LRa79HNVNf5tnm3QZpdrz85qzrM"',
//      date: 'Fri, 10 Feb 2023 07:36:52 GMT',
//      connection: 'close'
//    },
//    config: {
//      transitional: {
//        silentJSONParsing: true,
//        forcedJSONParsing: true,
//        clarifyTimeoutError: false
//      },
//      adapter: [ 'xhr', 'http' ],
//      transformRequest: [ [Function: transformRequest] ],
//      transformResponse: [ [Function: transformResponse] ],
//      timeout: 0,
//      xsrfCookieName: 'XSRF-TOKEN',
//      xsrfHeaderName: 'X-XSRF-TOKEN',
//      maxContentLength: -1,
//      maxBodyLength: -1,
//      env: { FormData: [Function], Blob: null },
//      validateStatus: [Function: validateStatus],
//      headers: AxiosHeaders {
//        Accept: 'application/json, text/plain, */*',
//        Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibW9vbiIsImlhdCI6MTY3NjAxNDYwNywiZXhwIjoxNjc2MDE1NTA3fQ.dhBclopUfZtwvr1qelfFUR6mS_a6B3fUKT0dsHhWNrs',
//        'User-Agent': 'axios/1.2.0',
//        'Accept-Encoding': 'gzip, deflate, br'
//      },
//      baseURL: 'http://localhost:8000',
//      withCredentials: true,
//      cookie: 'refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJ0ZXN0MUBuYXZlci5jb20iLCJpYXQiOjE2NzYwMTEzMjksImV4cCI6MTY3NjYxNjEyOX0.LjR5tcGvUAXHSW9qB2tLn3Te8-RaYNdEorZWnpxacGU',
//      method: 'get',
//      url: '/users/info?userId=1',
//      data: undefined
//    },
//    request: <ref *1> ClientRequest {
//      _events: [Object: null prototype] {
//        abort: [Function (anonymous)],
//        aborted: [Function (anonymous)],
//        connect: [Function (anonymous)],
//        error: [Function (anonymous)],
//        socket: [Function (anonymous)],
//        timeout: [Function (anonymous)],
//        prefinish: [Function: requestOnPrefinish]
//      },
//      _eventsCount: 7,
//      _maxListeners: undefined,
//      outputData: [],
//      outputSize: 0,
//      writable: true,
//      destroyed: false,
//      _last: true,
//      chunkedEncoding: false,
//      shouldKeepAlive: false,
//      maxRequestsOnConnectionReached: false,
//      _defaultKeepAlive: true,
//      useChunkedEncodingByDefault: false,
//      sendDate: false,
//      _removedConnection: false,
//      _removedContLen: false,
//      _removedTE: false,
//      _contentLength: 0,
//      _hasBody: true,
//      _trailer: '',
//      finished: true,
//      _headerSent: true,
//      _closed: false,
//      socket: Socket {
//        connecting: false,
//        _hadError: false,
//        _parent: null,
//        _host: 'localhost',
//        _readableState: [ReadableState],
//        _events: [Object: null prototype],
//        _eventsCount: 7,
//        _maxListeners: undefined,
//        _writableState: [WritableState],
//        allowHalfOpen: false,
//        _sockname: null,
//        _pendingData: null,
//        _pendingEncoding: '',
//        server: null,
//        _server: null,
//        parser: null,
//        _httpMessage: [Circular *1],
//        [Symbol(async_id_symbol)]: 187640,
//        [Symbol(kHandle)]: [TCP],
//        [Symbol(kSetNoDelay)]: false,
//        [Symbol(lastWriteQueueSize)]: 0,
//        [Symbol(timeout)]: null,
//        [Symbol(kBuffer)]: null,
//        [Symbol(kBufferCb)]: null,
//        [Symbol(kBufferGen)]: null,
//        [Symbol(kCapture)]: false,
//        [Symbol(kBytesRead)]: 0,
//        [Symbol(kBytesWritten)]: 0,
//        [Symbol(RequestTimeout)]: undefined
//      },
//      _header: 'GET /users/info?userId=1 HTTP/1.1\r\n' +
//        'Accept: application/json, text/plain, */*\r\n' +
//        'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibW9vbiIsImlhdCI6MTY3NjAxNDYwNywiZXhwIjoxNjc2MDE1NTA3fQ.dhBclopUfZtwvr1qelfFUR6mS_a6B3fUKT0dsHhWNrs\r\n' +
//        'User-Agent: axios/1.2.0\r\n' +
//        'Accept-Encoding: gzip, deflate, br\r\n' +
//        'Host: localhost:8000\r\n' +
//        'Connection: close\r\n' +
//        '\r\n',
//      _keepAliveTimeout: 0,
//      _onPendingData: [Function: nop],
//      agent: Agent {
//        _events: [Object: null prototype],
//        _eventsCount: 2,
//        _maxListeners: undefined,
//        defaultPort: 80,
//        protocol: 'http:',
//        options: [Object: null prototype],
//        requests: [Object: null prototype] {},
//        sockets: [Object: null prototype],
//        freeSockets: [Object: null prototype] {},
//        keepAliveMsecs: 1000,
//        keepAlive: false,
//        maxSockets: Infinity,
//        maxFreeSockets: 256,
//        scheduling: 'lifo',
//        maxTotalSockets: Infinity,
//        totalSocketCount: 1,
//        [Symbol(kCapture)]: false
//      },
//      socketPath: undefined,
//      method: 'GET',
//      maxHeaderSize: undefined,
//      insecureHTTPParser: undefined,
//      path: '/users/info?userId=1',
//      _ended: true,
//      res: IncomingMessage {
//        _readableState: [ReadableState],
//        _events: [Object: null prototype],
//        _eventsCount: 4,
//        _maxListeners: undefined,
//        socket: [Socket],
//        httpVersionMajor: 1,
//        httpVersionMinor: 1,
//        httpVersion: '1.1',
//        complete: true,
//        rawHeaders: [Array],
//        rawTrailers: [],
//        aborted: false,
//        upgrade: false,
//        url: '',
//        method: null,
//        statusCode: 200,
//        statusMessage: 'OK',
//        client: [Socket],
//        _consuming: false,
//        _dumped: false,
//        req: [Circular *1],
//        responseUrl: 'http://localhost:8000/users/info?userId=1',
//        redirects: [],
//        [Symbol(kCapture)]: false,
//        [Symbol(kHeaders)]: [Object],
//        [Symbol(kHeadersCount)]: 18,
//        [Symbol(kTrailers)]: null,
//        [Symbol(kTrailersCount)]: 0,
//        [Symbol(RequestTimeout)]: undefined
//      },
//      aborted: false,
//      timeoutCb: null,
//      upgradeOrConnect: false,
//      parser: null,
//      maxHeadersCount: null,
//      reusedSocket: false,
//      host: 'localhost',
//      protocol: 'http:',
//      _redirectable: Writable {
//        _writableState: [WritableState],
//        _events: [Object: null prototype],
//        _eventsCount: 3,
//        _maxListeners: undefined,
//        _options: [Object],
//        _ended: true,
//        _ending: true,
//        _redirectCount: 0,
//        _redirects: [],
//        _requestBodyLength: 0,
//        _requestBodyBuffers: [],
//        _onNativeResponse: [Function (anonymous)],
//        _currentRequest: [Circular *1],
//        _currentUrl: 'http://localhost:8000/users/info?userId=1',
//        [Symbol(kCapture)]: false
//      },
//      [Symbol(kCapture)]: false,
//      [Symbol(kNeedDrain)]: false,
//      [Symbol(corked)]: 0,
//      [Symbol(kOutHeaders)]: [Object: null prototype] {
//        accept: [Array],
//        authorization: [Array],
//        'user-agent': [Array],
//        'accept-encoding': [Array],
//        host: [Array]
//      }
//    },
//    data: { id: 1, nickname: 'moon', description: '안녕하세용', role: 'Client' }
//  }
